@startuml 消息推送系统
node 业务系统
queue 消息队列
node 推送服务器
cloud 浏览器
database 数据库

浏览器 -> 推送服务器: 建立websocket连接,保持心跳
业务系统 ==> 消息队列: 业务变更,发送消息
消息队列 ..> 推送服务器: 订阅消息
推送服务器 ..> 推送服务器: 查询自身socket连接
推送服务器 -> 数据库: 存数据库
推送服务器 -> 浏览器: 推送变更
@enduml