/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MyThread */

#ifndef _Included_MyThread
#define _Included_MyThread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MyThread
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MyThread_start
  (JNIEnv *env, jobject);

#ifdef __cplusplus
}
#endif
#endif
