@startuml
ConfigurationClassParser-> deferredImportSelectorHandler:handle 
ConfigurationClassParser-> deferredImportSelectorHandler:process
deferredImportSelectorHandler->DeferredImportSelectorGroupingHandler:register
DeferredImportSelectorGroupingHandler->DeferredImportSelectorGrouping:computeIfAbsent
DeferredImportSelectorGroupingHandler->DeferredImportSelectorGroupingHandler:processor
DeferredImportSelectorGroupingHandler->DeferredImportSelectorGrouping:getImports
deferredImportSelectorHandler->DefaultDeferredImportSelectorGroup:process
DefaultDeferredImportSelectorGroup->DeferredImportSelector:selectImport
@enduml
