apisix:
  node_listen: 9080              # 设置监听端口
  enable_ipv6: false             # 干掉IPV6
  allow_admin:                   
    - 0.0.0.0/0                  # 允许所有的网络访问,可配置为上游 F5 端点  0.0.0.0/0 支持所有网络访问
  admin_key:
    - name: "jinfuyun"           # 配置登陆账号
      key: 01fc6a5f60c5bc55a01fd0c0ad4895c5
      role: admin                # 提供了 admin/viewer 两种角色 admin 具有 读写权限/只读权限
etcd:
  host: # 配置 etcd 的多个节点和用户名密码
    - "http://etcd-1:2379"     # multiple etcd address
    - "http://etcd-2:2379"     # multiple etcd address
    - "http://etcd-3:2379"     # multiple etcd address
  prefix: "/apisix"               # apisix configurations prefix
  timeout: 30                     # 30 seconds
  user: root                     # 配置 etcd 账号
  password: YzYzMTFmM2M5MGEzMDljYmU4MWM5ZDcwYjQ2ZjJlNjMK  # 配置 ETCD 的密码
# 配置 prometheus 的相关属性
plugin_attr:
  prometheus:
    export_addr:
      ip: "0.0.0.0"
      port: 9091

